### ISSUE TITLE
Suggestions for pandas episode

### ISSUE THREAD

**Issue by bast** [AaltoSciComp/python-for-scicomp#105]
- [x] img/01_table_dataframe.svg missing? does not show up

- [x] tidy data: I found it useful for my understanding that in tidy data columns are variables and rows are measurements and I can add new measurements without changing the code that reads the data. One can also say that arranging data in tables in publication or presentation may not be the ideal way to arrange data for reading.

- [ ] one can say that pandas integrates nicely with plotting libraries like seaborn or altair (they are built around the concept of dataframes).

- [x] not sure it was mentioned but can be highlighted that dataframes carry useful statistics functions already built in.

**Comment by bast** [comment]
@wikfeldt

**Comment by wikfeldt** [comment]
that was quick, thanks! just added the figs in this PR and will review your other input

**Comment by wikfeldt** [comment]
ah sorry you already merged, i'll push the figs to master branch
