### ISSUE TITLE
9. dependency management

### ISSUE THREAD

**Issue by rkdarst** [AaltoSciComp/python-for-scicomp#11]
Check the pad, but as of this writing:

Dependencies management (Understand why dependencies must be tracked, and be able to make dependencies reproducible):
- Create a virtualenv and install requirements.txt
- Create a requirements.txt (by hand)
- Freeze virtualenv
- Know that both conda and pip/venv/PyPI are popular packaging/dependency management tools and knowing when to prefer the one or other
- Be able to communicate the dependencies as part of a report/thesis/publication

**Comment by bast** [comment]
More notes to me:
- requirements.txt pointing to github repo
- as narrow as possible for publications but as wide as possible for libraries

Would be nice if we could not only discuss what might happen 2 years later with dependencies but if we could experience it in an exercise.

**Comment by bast** [comment]
Also mention poetry, pipenv, flit.

**Comment by bast** [comment]
- tracking dependencies in setup.py versus requirements.txt

**Comment by bast** [comment]
I am working on an iteration based on Anne's structure as starting point.
