### ISSUE TITLE
dependencies: comments from 2021

### ISSUE THREAD

**Issue by rkdarst** [AaltoSciComp/python-for-scicomp#204]
* Exercise times add up to 60 minutes in one-hour lesson.  The timings need to be adjusted.
* It should be clear that for most people, it is exercise 2 or 3 (most people wouldn't do both).

**Comment by bast** [comment]
The lesson has been rewritten and this has been addressed. Currently the lesson is scheduled for 30 mins and I will extend it to 45 mins on webpage and the planning document.
