### ISSUE TITLE
parallel: mention performance boosting before gonig too deep to parallelizm (numba, cython)

### ISSUE THREAD

**Issue by rkdarst** [AaltoSciComp/python-for-scicomp#215]
"Before you spend too much time parallelizing, also check out these performance boosting tools".  numba and cython.  We can link to here:
https://enccs.github.io/HPDA-Python/performance-boosting/

**Comment by wikfeldt** [comment]
fixed in [d10b814](https://github.com/AaltoSciComp/python-for-scicomp/pull/224/commits/d10b8149fcc54019cb4ad9c860fd09c2e620ba53)
