### ISSUE TITLE
parallel python

### ISSUE THREAD

**Issue by rkdarst** [AaltoSciComp/python-for-scicomp#23]
From chat, we need a lesson on parallel python.  It doesn't have to be long, but should introduce some things.

- GIL
  - Exercise: Given several snipets of code, which ones can and can not be made multithreaded?  (Can anyone think of some tricky cases?)
  - Example that can be done in Jupyter, to show that something can't be parallel?
- Multiprocessing
  - Exercise: parallel reduce using a process pool
- OpenMP ?
- MPI ?

I can do at least the GIL and multiprocessing part (but would be happy if someone else dit).  I am  not the best person for the last two.

**Comment by bast** [comment]
Followed-up in #98.
