### ISSUE TITLE
Polars as an alternative to Pandas

### ISSUE THREAD

**Issue by eglerean** [AaltoSciComp/python-for-scicomp#282]
Polars is a rust based alternative to Pandas. I could include a note box in the materials for those who want to try it. Do you think this is a good idea?

**Comment by eglerean** [comment]
Here on why this is not like dask or other similar libraries for large datasets https://blog.jetbrains.com/pycharm/2024/07/polars-vs-pandas/

**Comment by bast** [comment]
+1 for adding a note that it exists so that people can explore it.
