### ISSUE TITLE
Follow-up suggestions for xarray lesson

### ISSUE THREAD

**Issue by bast** [AaltoSciComp/python-for-scicomp#295]
These are follow-ups from #283:
- "Would be cool if we could grab the data from a Google search query or some table somewhere, instead of having to make something up entirely.": https://github.com/AaltoSciComp/python-for-scicomp/pull/283#discussion_r1812664388
- "Let's make it super clear that these are the Data Variables.": https://github.com/AaltoSciComp/python-for-scicomp/pull/283#discussion_r1812662758

**Comment by eglerean** [comment]
@wmvanvliet @gregordecristoforo if you think this was solved in recent merges, please close this issue :)

**Comment by wmvanvliet** [comment]
first point is still an open issue
