### ISSUE TITLE
1: jupyter

### ISSUE THREAD

**Issue by rkdarst** [AaltoSciComp/python-for-scicomp#3]
Jupyter:
- Understand why Jupyter exists and when to *not* use it! (good for exploration and figure generation for supporting material)
- Make a notebook and run cells.

Especially at the beginning, we have to think about bootstraping people, and getting the Jupyter to work.  This somehow relates to the installation.

**Comment by eglerean** [comment]
The page misses questions and keypoints. I can make a pull request with questions and keypoints from

https://coderefinery.github.io/jupyter/01-motivation/

?

**Comment by rkdarst** [comment]
I will convert this lesson to jupyter format (as a self-demonstrating example) and add some content.

**Comment by bast** [comment]
I think this is done.
