### ISSUE TITLE
need fix locally to make sphinx work with sphinx_lesson 

### ISSUE THREAD

**Issue by wikfeldt** [AaltoSciComp/python-for-scicomp#36]
if i don't add this:
```
import sys
sys.path.append('.')
```
to conf.py sphinx-build fails with 
`Could not import extension sphinx_lesson (exception: No module named 'sphinx_lesson')`
But i could be misunderstanding something...

**Comment by rkdarst** [comment]
Have you installed the requirement.txt in a virtualenv?  That's how I
have been using it, it depends on these external packages.

Did you locally clone sphinx_lesson?

**Comment by wikfeldt** [comment]
yeah i pip installed myst_nb but requirements are satisfied, still doesn't work without sphinx_lesson inside lesson directory and that sys.path.append command in conf.py

**Comment by rkdarst** [comment]
sphinx-lesson is also a dependency:

in requirements.txt:
```
https://github.com/coderefinery/sphinx-lesson/archive/master.zip
```

Is this installed?

**Comment by wikfeldt** [comment]
rerunning `pip install -r requirements.txt` solved the issue, closing
