### ISSUE TITLE
Ideas for plotting exercises

### ISSUE THREAD

**Issue by bast** [AaltoSciComp/python-for-scicomp#37]
Currently:
- 4.1: recreate a figure
- 4.2: create data and plot as histogram
- 4.3: create data and plot on logarithmic scale
- 4.4: warhol-like print

Suggestions:
- 4.1: takes too much time, I recommend I provide the data and a simple example and the exercise is to create a plot
- 4.2: I prefer to provide data so that we don't spend time on thinking about how the bell curve worked again
- 4.3: same here, provide data that looks bad on normal scale and exercise is to bring it to log scale
- 4.4: I would remove this

Add exercise:
- Port stateful to OO
- Provide an example on how to fetch CSV file from the web and plot and give few CSV examples and let learners choose an appropriate example from gallery and adapt it to our needs

**Comment by bast** [comment]
For the CSV examples (learner chooses one):
- some scatter plot
- histogram
- heatmap
- something geospatial

**Comment by bast** [comment]
Idea for 4.1: provide data for https://seaborn.pydata.org/examples/anscombes_quartet.html and let learners add a linear regression. This data set is a classic and used as an example why looking at data alone without plotting it can be dangerous.

**Comment by samumantha** [comment]
Agreed, the datasets used for plotting should be as simple as possible. Stateful porting to oo is a good exercise since when googling problems both come up mixed and things do not work if you don't know about the two ways of doing things. As something geospatial, maybe plotting a tif, like digital elevation model ?

**Comment by samumantha** [comment]
same here.

**Comment by annefou** [comment]
I like your plan @bast 
You probably have it but  is there some details on how to customize your plots (changing font size, labels, etc.). I see too many researchers importing png file in powerpoints and overwritting labels, titles. Not so good for repeatability/reproducibility.

**Comment by bast** [comment]
Good point, I will add such a section.
