### ISSUE TITLE
2. numpy

### ISSUE THREAD

**Issue by rkdarst** [AaltoSciComp/python-for-scicomp#4]
Check the pad for contents of this section, but as of this writing:

```
Numpy (Understand enough of numpy to seach for answers to the rest of your questions):
- Numpy organization
  - What is the array data structure?
  - Why is the array data structure good?
  - Understand when numpy arrays are still slow
  - Why learn numpy?  You rarely use it directly, but almost any other package uses it.
- Array data structure
  - Types
  - Shape
- Slice arrays, basic and fancy
- Types of operations: scalar, ufunc, methods, functions
- Basic linear algebra
```

**Comment by samumantha** [comment]
gonna rearrange the lesson according to cryptpad and think about exercises now

**Comment by samumantha** [comment]
What is meant by 'fancy slicing'? slicing with lists?
And what is meant by 'Types of operations: scalar, ufunc, methods, functions' ? Something like np.dot(x,y) vs x.doy(y) ? What is what?

**Comment by samumantha** [comment]
To be done: some exercises still need solutions, keypoint adjustment

**Comment by samumantha** [comment]
to be done: solution check and add exercise numbers to challenge boxes

**Comment by samumantha** [comment]
not sure what is wrong with the last codeblock in types and operations, it does not come out as codeblock on the webpage?

**Comment by rkdarst** [comment]
> not sure what is wrong with the last codeblock in types and operations, it does not come out as codeblock on the webpage?

It needed to be more intended: it was indented the same as the
paragraph of the bullet point would be.  I have adjusted it some and
am pushing directly.

**Comment by naoe-tatara** [comment]
Can you add link to the NumPy document (https://numpy.org/doc/stable/), probably at the very top or as a reference at the end of the lesson?

**Comment by bast** [comment]
I understand that everything has been followed up. Closing.
