### ISSUE TITLE
jupyter-execute throws many warnings when running locally

### ISSUE THREAD

**Issue by bast** [AaltoSciComp/python-for-scicomp#40]
But I don't know what it's doing.

It also creates files locally which are not tracked or ignored.

**Comment by bast** [comment]
```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
	jupyter_execute/
	titanic.csv
	titanic.csv.1
	titanic.csv.2
	titanic.csv.3
	titanic.csv.4
	titanic.csv.5
```

**Comment by rkdarst** [comment]
What warnings do you get?  I see only one

**Comment by bast** [comment]
When you build several times, you get more warnings, something recursively accumulates there.

**Comment by rkdarst** [comment]
The titanics come because the notebook executes `wget` on some data, each new time making a new file because it's not set to override.  But that whole thing probably depends on Linux command line utilities being present, so should be changed.

**Comment by bast** [comment]
Problem shows up when using `sphinx-build`. Richard found a solution. I am sending a PR very soon.
