### ISSUE TITLE
3. matplotlib

### ISSUE THREAD

**Issue by rkdarst** [AaltoSciComp/python-for-scicomp#5]
Check the pad, but as of this writing:

```
Matplotlib
- Know it exists
- Make a simple plot
- object-oriented vs stateful interface?
  - Demonstrate same code with OO and stateful
  - Exercise: convert between them
- Headless rendering by setting backend
- Other options
  - Seaborn
  - vs R tools
```

**Comment by samumantha** [comment]
What is meant by  'headless rendering by setting backend' ?

**Comment by rkdarst** [comment]
Roughly this:

import matplotlib
matplotlib.use("Agg")

Basically, the steps needed to run it on a remote server, when you
don't have a display ('headless' jargon).  Occassionally we get people
with this problem.

And I guess also whatever steps needed to run in Jupyter...

**Comment by eglerean** [comment]
Hi

text looks fine. I didn't do all exercises as I don't have time right now. Are you thinking of releasing the solutions? Surely people will ask (I can help with the solutions which should live on a different place not easily accessible by the students)

**Comment by annefou** [comment]
Should we add something about about the two interfaces:

What is matplotlib? Why should we learn to use it?
----------------------------------------------------

While python offers a large range of python packages for plotting spatio-temporal data, we will focus here on the most generic python interface to create maps. Most of other python packages used for plotting spatio-temporal data are based on matplotlib.

## The main principle of matplotlib

First, matplotlib has two user interfaces:

* The first mimics MATLAB plotting and uses the pylab interface.
* The second option is an object-oriented interface which is much more powerful.

When plotting with matplotlib, it is very important to know and understand that there are two approaches even though the reasons of this dual approach is outside the scope of this lesson.

When searching for help on the internet, you will find solutions where the two approaches are mixed which may be very confusing for you. The best for new codes is to stick to the object-oriented interface and this is what we will show in this lesson.

**New matplotlib users should learn and use the object oriented interface.**

**Comment by annefou** [comment]
It may be useful to show  https://matplotlib.org/faq/usage_faq.html#parts-of-a-figure

Understanding the notion of Figure, axes, etc. is quite useful. the approach in python is different from R and R users may be a bit confused without some basic principles on how to build a figure with matplotlib.

**Comment by bast** [comment]
Thanks for good input here. I will soon send a PR taking these points into an episode "skeleton" and closing this issue. I will also suggest to change the examples. I want to make them simpler and less geared towards engineering disciplines. Also some social science stuff.
