### ISSUE TITLE
4. scripts

### ISSUE THREAD

**Issue by rkdarst** [AaltoSciComp/python-for-scicomp#6]
Check the pad, but as of this writing:

Scripts (Be able to make repeatable and automatable scripts, and run them with different options/inputs without modifying the scripts.  Backdoor introduction to the command line):
- create a script with #!.  It should take two command line arguments and multiply them
- create a module: make your previous file importable
- parse command line arguments (use argparse, introduce click)

**Comment by annefou** [comment]
I guess this episode has a higher priority than scipy so I can work on it now.

**Comment by eglerean** [comment]
I have reviewed this page. No typos and all code works fine. No changes needed from my side.

Just a tiny comment: I am not 100% sure if it is good to have the "Synchronize with Jupytext" part in the middle, it requires installing extra packages and might slow down some users. Maybe it can be moved at the end if there is more time?

For the future: the final example on calling other scripts could be used as an initial introduction on how to build a pipeline as a series of scripts called sequentially by the pipeline script. (one for loading, one for processing, one for visualisation and storage). This is the most simple pipeline, some users might have never seen one so it could be a nice scripting exercise? 
Then later they can learn "better" ways like covered in the CR material (e.g. snakemake).

**Comment by annefou** [comment]
@eglerean  Many thanks for your review of the episode. You are right for Jupytext: I will move it to the end.

**Comment by bast** [comment]
I understand that everything has been followed up. Closing.
