### ISSUE TITLE
numpy: matrix class not recommended

### ISSUE THREAD

**Issue by bast** [AaltoSciComp/python-for-scicomp#67]
https://numpy.org/doc/stable/reference/generated/numpy.matrix.html

but it's used in some exercise

**Comment by bast** [comment]
> It is no longer recommended to use this class, even for linear algebra. Instead use regular arrays. The class may be removed in the future.

**Comment by rkdarst** [comment]
is there enough info if I completely remove the last bit amount matrices and there are no exercises there?  I think it's probably good time-wise, but are we getting short on advanced content?

Option is to replace it with some other intermediate topic (1-2 paragraphs worth)

**Comment by bast** [comment]
If we are worried about too little material, I would add matrix multiplication or matrix diagonalization.

**Comment by eglerean** [comment]
Also in the two breakout rooms where I was the class matrix felt obsolete and they did not understand the point of it. I would drop that part and maybe if there is really time for extra exercises, the last chunk of optional exercises is enough to cover any extra spare time.
