### ISSUE TITLE
5. packaging

### ISSUE THREAD

**Issue by rkdarst** [AaltoSciComp/python-for-scicomp#7]
Check the pad, but as of now:

Packaging:
- What is PyPI?  What is pip?  What is conda?
- README and docs
- Setup.py for distributing packages

**Comment by annefou** [comment]
@bast Happy to take some part to help you on this episode.

**Comment by bast** [comment]
Thanks! I will add some more coarse structure and then create more fine-grained issues and I will take the ones that I will start working on.
