### ISSUE TITLE
7. pandas

### ISSUE THREAD

**Issue by rkdarst** [AaltoSciComp/python-for-scicomp#9]
Check the pad, but as of this writing:

(TW) Pandas (Understand enough to be self-sufficient when learning more about it):
- Learn a new package: pandas
  - Find website, find docs, find the first tutorial
  - https://coderefinery.github.io/jupyter/05-exercises/#data-analysis-with-pandas-dataframes
- Organization
  - DataFrames
  - Series
  - Types
- Concept of tidy data (https://vita.had.co.nz/papers/tidy-data.pdf, wikipedia)
- Example:
  - Reading data from CSV, manipulating it
    - Load an excel spreadsheet
  - Indexing and slicing
  - Filtering
  - Write it out

**Comment by wikfeldt** [comment]
very good tutorial material here: https://pandas.pydata.org/docs/getting_started/intro_tutorials/

**Comment by bast** [comment]
Can this issue be closed or is something listed above that we should not forget to add at some point?

**Comment by wikfeldt** [comment]
nothing from above list missing in pandas episode, so closing
