### ISSUE TITLE
Episode: parallel processing

### ISSUE THREAD

**Issue by rkdarst** [AaltoSciComp/python-for-scicomp#98]
- Modes of parallelism, RD
- multithreading and GIL (quick since not really used, RD)
- multiprocessing (example, RD)
- MPI
- Couple in other languages (e.g. openmp, RB)
- dask and task queues (mention)

**Comment by wikfeldt** [comment]
the MPI section in this episode can link to these introductory MPI lessons where python is included:
- https://rantahar.github.io/introduction-to-mpi/
- https://pdc-support.github.io/introduction-to-mpi/

**Comment by wikfeldt** [comment]
also these blog posts are good for gentle MPI / mpi4py introduction:
- https://www.kth.se/blogs/pdc/2019/08/parallel-programming-in-python-mpi4py-part-1/
- https://www.kth.se/blogs/pdc/2019/11/parallel-programming-in-python-mpi4py-part-2/

and these two posts introduce multiprocessing:
- https://www.kth.se/blogs/pdc/2019/02/parallel-programming-in-python-multiprocessing-part-1/
- https://www.kth.se/blogs/pdc/2019/03/parallel-programming-in-python-multiprocessing-part-2/

**Comment by bast** [comment]
From #23:

> - GIL
>   - Exercise: Given several snipets of code, which ones can and can not be made multithreaded?  (Can anyone think of some tricky cases?)
>   - Example that can be done in Jupyter, to show that something can't be parallel?
> - Multiprocessing
>   - Exercise: parallel reduce using a process pool
> - OpenMP ?
> - MPI ?

**Comment by bast** [comment]
I am today working on the MPI part and will try to get the above suggestions into the text and resolve this issue.
